name: stackfar
title: Stackfar - Local copy of StackExchange
base: core18
version: '0.0.1'
summary: Stackfar is an offline version of any of your favorite stackexchange websites.
description: |
  Stackfar is an offline version of any stackexchange website. It will download latest datadumps automatically. It's still very much in alpha.
confinement: strict
grade: devel


apps:
  webserver:
    command: run_webserver
    daemon: simple
    plugs: [network-bind]
  syncer:
    command: syncer
    daemon: simple
    plugs: [network]


parts:
  webserver:
    source: .
    plugin: go
    go-packages: ["github.com/ryanjyoder/stackfar/cmd/webserver"]
    build-packages:
      - git
    override-build: |
      export GO111MODULE=on
      go build cmd/webserver/webserver.go
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp webserver $SNAPCRAFT_PART_INSTALL/bin/
    stage: [bin/webserver]

  syncer:
    source: .
    plugin: dump
    stage: 
      - bin
      - etc
      - lib
      - template
      - usr
      - var
    stage-packages:
      - rsync 

